lint vimrc

diff --git a/vim/vimrc b/vim/vimrc
--- a/vim/vimrc
+++ b/vim/vimrc
@@ -1,16 +1,18 @@
+set encoding=utf-8
+scriptencoding utf-8
 " clear previous variable settings
 filetype on
 filetype plugin indent on
 syntax on
 
-if empty(glob("~/.vim/autoload/plug.vim"))
+if empty(glob('~/.vim/autoload/plug.vim'))
     " Download the actual plugin manager
     silent execute '!mkdir -p ~/.vim/autoload/'
     silent execute '!wget -P ~/.vim/autoload https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
 endif
 
 
-if !has("compatible")
+if !has('compatible')
    call plug#begin('~/.vim/plugged')
    " Appearance
    Plug 'altercation/vim-colors-solarized'
@@ -46,17 +48,17 @@ if !has("compatible")
 
    call plug#end()
 endif
-let mapleader="\<Space>"
+let g:mapleader="\<Space>"
 
 " Plugins
 " solarized
 set background=light
-let g:solarized_visibility="high"
-let solenv=$SOLVAR
-if solenv == "light"
+let g:solarized_visibility='high'
+let g:solenv=$SOLVAR
+if g:solenv ==? 'light'
    set background=light
 endif
-if solenv == "dark"
+if g:solenv ==? 'dark'
    set background=dark
 endif
 silent! colorscheme solarized
@@ -69,8 +71,8 @@ nnoremap <F6> :update<CR>:Dispatch<CR>
 "" Prompt for a command to run
 nnoremap <F7> :update<CR>:FocusDispatch
 "" run make
-let target = ""
-nnoremap <F8> :let target = ""<left>
+let g:target = ''
+nnoremap <F8> :let g:target = ""<left>
 "" run make
 nnoremap <F9> :update<CR>:exe 'Make '.target<Cr>
 
@@ -79,16 +81,16 @@ let g:syntastic_always_populate_loc_list = 1
 let g:syntastic_auto_loc_list = 0 " Don't auto open/close location list
 let g:syntastic_check_on_open = 0 " Never run syntastic automatically
 let g:syntastic_check_on_wq = 0   " Never run syntastic automatically
-let g:syntastic_mode_map={"mode" : "passive"}
+let g:syntastic_mode_map={'mode' : 'Passive'}
 let g:syntastic_enable_signs=1
-let g:syntastic_quiet_messages = { "regex": "\\max"}
-if executable("ifort")
-   let g:syntastic_fortran_compiler = "ifort"
-   let g:syntastic_fortran_compiler_options = "-no-save-temps
-            \ -y -warn -nogen-interfaces"
+let g:syntastic_quiet_messages = { 'regex': '\max'}
+if executable('ifort')
+   let g:syntastic_fortran_compiler = 'ifort'
+   let g:syntastic_fortran_compiler_options = '-no-save-temps
+            \ -y -warn -nogen-interfaces'
 else
-   let g:syntastic_fortran_compiler = "gfortran"
-   let g:syntastic_fortran_compiler_options = "-Wall -O0"
+   let g:syntastic_fortran_compiler = 'gfortran'
+   let g:syntastic_fortran_compiler_options = '-Wall -O0'
 endif
 "command to run syntastic
 nnoremap <leader>sc :update<CR>:SyntasticCheck<CR>
@@ -129,30 +131,29 @@ nnoremap <leader>u :GundoToggle<CR>
 
 "
 "Own functions
-if !has("compatible")
+if !has('compatible')
    set nrformats=octal,hex,alpha
    function! Incr()
-      let a = line('.') - line("'<")
-      let c = virtcol("'<")
-      if a > 0
-         execute 'normal! '.c.'|'.a."\<C-a>"
+      let l:a = line('.') - line("'<")
+      let l:c = virtcol("'<")
+      if l:a > 0
+         execute 'normal! '.l:c.'|'.l:a."\<C-a>"
       endif
-      normal `<
+      normal! `<
    endfunction
    vnoremap <C-a> :call Incr()<CR>
    function! GenerateCtags()
-      let ctagdir = substitute(system('git rev-parse --git-dir 2> /dev/null || echo -n "."'), '[[:cntrl:]]', '', 'g')
-      let ctagwdir = substitute(system('git rev-parse --show-toplevel 2> /dev/null || echo -n "."'), '[[:cntrl:]]', '', 'g')
-      echom ctagwdir
-      echom ctagdir
-      execute '!ctags -R --tag-relative=yes -f"'.ctagdir.'/tags" '.ctagwdir
+      let l:ctagdir = substitute(system('git rev-parse --git-dir 2> /dev/null || echo -n "."'), '[[:cntrl:]]', '', 'g')
+      let l:ctagwdir = substitute(system('git rev-parse --show-toplevel 2> /dev/null || echo -n "."'), '[[:cntrl:]]', '', 'g')
+      echom l:ctagwdir
+      echom l:ctagdir
+      execute '!ctags -R --tag-relative=yes -f"'.l:ctagdir.'/tags" '.l:ctagwdir
       e!
    endfunction
    command! MakeCtags :call GenerateCtags()
 endif
 
 " General Settings
-set encoding=utf-8
 set spelllang=en_us
 set hidden
 set path+=** "fuzzy search
@@ -181,10 +182,12 @@ set statusline+=%=                           " right align remainder
 set statusline+=%5(%l%),%-9(%c%V%)\          " line, character
 
 " now set it up to change the status line based on mode
-if version >= 700
+if v:version >= 700
    highlight StatusLine ctermfg=6 ctermbg=0
-   autocmd InsertEnter * highlight StatusLine ctermfg=3 ctermbg=0
-   autocmd InsertLeave * highlight StatusLine ctermfg=6 ctermbg=0
+   augroup statusHighlight
+      autocmd InsertEnter * highlight StatusLine ctermfg=3 ctermbg=0
+      autocmd InsertLeave * highlight StatusLine ctermfg=6 ctermbg=0
+   augroup END
 endif
 "}
 
@@ -202,10 +205,12 @@ set nolist  " list disables linebreak
 highlight ExtraWhitespace ctermbg=9
 "Highlight ExtraWhitespace
 match ExtraWhitespace /\s\+$/
-autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
-autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
-autocmd InsertLeave * match ExtraWhitespace /\s\+$/
-autocmd BufWinLeave * call clearmatches()
+augroup extraWhitespaceHighlight
+   autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
+   autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
+   autocmd InsertLeave * match ExtraWhitespace /\s\+$/
+   autocmd BufWinLeave * call clearmatches()
+augroup end
 " Indentation settings for using 3 spaces instead of tabs.
 set shiftwidth=3
 set softtabstop=3
@@ -266,13 +271,13 @@ nnoremap <leader>ev :vsplit $MYVIMRC<CR>
 nnoremap <leader>sv :source $MYVIMRC<CR>
 
 "folding
-if !has("compatible")
+if !has('compatible')
    set nofoldenable
 endif
 set foldmethod=manual
 set foldlevel=0
 set foldnestmax=2
-let fortran_fold=1
+let g:fortran_fold=1
 nnoremap <leader>fo :let &foldmethod=b:wantedfoldmethod<CR>
 
 "File type specific settings
@@ -280,9 +285,9 @@ nnoremap <leader>fo :let &foldmethod=b:wantedfoldmethod<CR>
 autocmd BufNewFile,BufFilePre,BufRead *.md setlocal filetype=markdown
 autocmd FileType markdown setlocal spell
 "Fortran
-let fortran_free_source=1
-let fortran_do_enddo=1
-let fortran_have_tabs=1
+let g:fortran_free_source=1
+let g:fortran_do_enddo=1
+let g:fortran_have_tabs=1
 autocmd FileType fortran let b:wantedfoldmethod="syntax"
 autocmd FileType fortran setlocal textwidth=132
 "python
@@ -295,7 +300,7 @@ autocmd Filetype python
          \ setlocal autoindent |
          \ setlocal fileformat=unix
 
-let python_highlight_all=1
+let g:python_highlight_all=1
 autocmd FileType python let b:wantedfoldmethod="indent"
 " cpp
 autocmd FileType cpp let b:wantedfoldmethod="syntax"
@@ -310,23 +315,23 @@ autocmd FileType gnuplot setlocal commentstring =#\ %s
 " Initialize Directories
 if has('persistent_undo')      "check if your vim version supports it
    function! InitializeDirectories()
-      let parent = "/tmp/".$USER.""
-      let prefix = '.vim/'
-      let dir_list = { 'undo/': 'undodir'}
+      let l:parent = '/tmp/'.$USER.''
+      let l:prefix = '.vim/'
+      let l:dir_list = { 'undo/': 'undodir'}
 
-      for [dirname, settingname] in items(dir_list)
-         let directory = parent . '/' . prefix . dirname . "/"
-         if exists("\*mkdir")
-            if !isdirectory(directory)
-               call mkdir(directory, "p")
+      for [l:dirname, l:settingname] in items(l:dir_list)
+         let l:directory = l:parent . '/' . l:prefix . l:dirname . '/'
+         if exists('\*mkdir')
+            if !isdirectory(l:directory)
+               call mkdir(l:directory, 'p')
             endif
          endif
-         if !isdirectory(directory)
-            echo "Warning: Unable to create backup directory: " . directory
-            echo "Try: mkdir -p " . directory
+         if !isdirectory(l:directory)
+            echo 'Warning: Unable to create backup directory: ' . l:directory
+            echo 'Try: mkdir -p ' . l:directory
          else
-            let directory = substitute(directory, " ", "\\\\\\\\ ", "")
-            exec "set " . settingname . "=" . directory
+            let l:directory = substitute(l:directory, ' ', '\\ ', '')
+            exec 'set ' . l:settingname . '=' . l:directory
          endif
       endfor
    endfunction
